# Load Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Load user configurations
source "$HOME/.environment"
source "$HOME/.private"
source "$HOME/.aliases"
source "$HOME/.functions"
source "$HOME/.ansi"

# Load SDKMAN!
source "$HOME/.sdkman/bin/sdkman-init.sh"

# Load NVM
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"

# redocly auto-completion
_redocly_yargs_completions()
{
  local reply
  local si=$IFS
  IFS=$'
' reply=($(COMP_CWORD="$((CURRENT-1))" COMP_LINE="$BUFFER" COMP_POINT="$CURSOR" redocly --get-yargs-completions "${words[@]}"))
  IFS=$si
  _describe 'values' reply
}
compdef _redocly_yargs_completions redocly

## Brew auto-completion
if type brew &>/dev/null
then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
fi

# Load starship
eval "$(starship init zsh)"

eval "$(pyenv init - > /dev/null 2>&1)"
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init - > /dev/null 2>&1)" ; fi
