#!/usr/bin/env bash

# Install HomeBrew if not yet installed
if test ! "$(which brew)"; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# Install all dependencies configured in the Brewfile
brew update
brew upgrade
brew tap homebrew/bundle
brew bundle --file ./Brewfile
brew cleanup
