#!/usr/bin/env bash

# Create a backup of a file by moving it and appending ".backup" to its name
backup() {
  target=$1
  if [ -e "$target" ]; then
    if [ ! -L "$target" ]; then
      mv "$target" "$target.backup"
      echo "$target was backed up to $target.backup"
    fi
  fi
}

# Create a symlink of a file
symlink() {
  file=$1
  link=$2
  if [ ! -e "$link" ]; then
    echo "Creating link of $file to $link"
    ln -s "$file" "$link"
  fi
}

# Iterate over the files in dotfiles and create links to them in the home directory
for file in dotfiles/*; do
  if [ ! -d "$file" ]; then
    target="$HOME/.$(basename "$file")"
    backup "$target"
    symlink "$PWD/$file" "$target"
  fi
done
