#!/usr/bin/env bash

source ../functions.sh

# Install SDKMAN! if not yet installed
if [ ! -f "$HOME/.sdkman/bin/sdkman-init.sh" ]; then
  curl -s "https://get.sdkman.io" | bash
fi

# Load SDKMAN!
source "$HOME/.sdkman/bin/sdkman-init.sh"

# Symlink custom config for SDKMAN!
backup "$HOME"/.sdkman/etc/config
symlink ./config.properties "$HOME"/.sdkman/etc/config

# Install common SDKs
sdk install java 21.0.1-amzn
sdk install gradle
